# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FUROYeiUGQGyVEgD-zHXM_BKM2lluyo
"""

"""
Modelling Script - Drug Classification
Kriteria 2: Membangun Model Machine Learning (Basic Level)
Dataset: drug200.csv
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import mlflow
import mlflow.sklearn
import warnings
warnings.filterwarnings('ignore')


# =====================================================================
# LOAD DATA
# =====================================================================
def load_data():
    """Load preprocessed data"""
    print("="*60)
    print("LOADING PREPROCESSED DATA")
    print("="*60)

    X_train = pd.read_csv('X_train.csv')
    X_test = pd.read_csv('X_test.csv')
    y_train = pd.read_csv('y_train.csv').values.ravel()
    y_test = pd.read_csv('y_test.csv').values.ravel()

    print(f"✓ X_train shape: {X_train.shape}")
    print(f"✓ X_test shape: {X_test.shape}")
    print(f"✓ y_train shape: {y_train.shape}")
    print(f"✓ y_test shape: {y_test.shape}")

    return X_train, X_test, y_train, y_test


# =====================================================================
# TRAIN MODEL
# =====================================================================
def train_model(X_train, X_test, y_train, y_test, model_name="DecisionTree"):
    """Train model dengan MLflow autolog"""
    print(f"\n{'='*60}")
    print(f"TRAINING MODEL: {model_name}")
    print("="*60)

    # Set experiment name
    mlflow.set_experiment("Drug_Classification_Experiment")

    # START RUN
    with mlflow.start_run(run_name=f"{model_name}_Model"):

        # Autolog harus ada DI DALAM start_run!
        mlflow.sklearn.autolog(log_models=True)

        # Pilih model
        if model_name == "DecisionTree":
            model = DecisionTreeClassifier(
                random_state=42,
                max_depth=10,
                min_samples_split=5
            )
        elif model_name == "RandomForest":
            model = RandomForestClassifier(
                n_estimators=100,
                random_state=42,
                max_depth=10
            )
        else:
            raise ValueError(f"Unknown model: {model_name}")

        # Train model
        print(f"\nTraining {model_name}...")
        model.fit(X_train, y_train)

        # Predict test set
        y_pred = model.predict(X_test)

        # Manual metric logging supaya tampil lengkap di MLflow
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')
        recall = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')

        # PRINT hasil
        print(f"\n{'='*60}")
        print("MODEL PERFORMANCE")
        print("="*60)
        print(f"Accuracy : {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall   : {recall:.4f}")
        print(f"F1-score : {f1:.4f}")

        # LOG KE MLFLOW
        mlflow.log_metric("test_accuracy", accuracy)
        mlflow.log_metric("test_precision", precision)
        mlflow.log_metric("test_recall", recall)
        mlflow.log_metric("test_f1_score", f1)

        mlflow.log_param("dataset_total", len(X_train) + len(X_test))
        mlflow.log_param("train_rows", len(X_train))
        mlflow.log_param("test_rows", len(X_test))

        print("\n✓ Model logged to MLflow!")
        print(f"✓ Run name: {model_name}_Model")

        # ============================================================
        # SAVE RUN INFO FOR CI/CD WORKFLOW
        # ============================================================
        run_id = mlflow.active_run().info.run_id
        artifact_uri = mlflow.get_artifact_uri()

        with open('run_info.txt', 'a') as f:
            f.write(f"MODEL: {model_name}\n")
            f.write(f"Run ID: {run_id}\n")
            f.write(f"Accuracy: {accuracy:.4f}\n")
            f.write(f"Precision: {precision:.4f}\n")
            f.write(f"Recall: {recall:.4f}\n")
            f.write(f"F1-Score: {f1:.4f}\n")
            f.write(f"Artifact URI: {artifact_uri}\n")
            f.write("="*40 + "\n")

        return model


# =====================================================================
# MAIN
# =====================================================================
def main():
    print("\n" + "="*60)
    print("DRUG CLASSIFICATION - MLFLOW TRAINING")
    print("="*60)

    # Load data
    X_train, X_test, y_train, y_test = load_data()

    # Train both models
    models = ["DecisionTree", "RandomForest"]

    for model_name in models:
        train_model(X_train, X_test, y_train, y_test, model_name)
        print("\n")

    print("="*60)
    print("TRAINING COMPLETED!")
    print("="*60)

    print("\nUntuk melihat hasil di MLflow UI:")
    print("1. Buka terminal")
    print("2. Jalankan:  py -m mlflow ui")
    print("3. Buka browser: http://localhost:5000")


if __name__ == "__main__":
    main()